# Generated by Django 4.2.6 on 2023-10-30 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='React',
            fields=[
                ('symbol', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('actual_price', models.FloatField(max_length=5)),
                ('date', models.DateField(max_length=200)),
            ],
        ),
    ]
