# Generated by Django 4.2.6 on 2023-10-29 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='React',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=200)),
                ('actual_price', models.FloatField(max_length=5)),
                ('date', models.DateField()),
            ],
        ),
    ]
