# Generated by Django 4.2.6 on 2023-10-31 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_react_date_alter_react_symbol'),
    ]

    operations = [
        migrations.AddField(
            model_name='react',
            name='monitor',
            field=models.IntegerField(default=10, max_length=5),
            preserve_default=False,
        ),
    ]
