# Generated by Django 4.2.6 on 2023-10-31 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_react_monitor'),
    ]

    operations = [
        migrations.AddField(
            model_name='react',
            name='high',
            field=models.FloatField(default=-1, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='react',
            name='low',
            field=models.FloatField(default=-1, max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='react',
            name='monitor',
            field=models.IntegerField(),
        ),
    ]
