# Generated by Django 4.2.6 on 2023-10-31 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_react_tunel_max_react_tunel_min'),
    ]

    operations = [
        migrations.RenameField(
            model_name='react',
            old_name='tunel_max',
            new_name='max',
        ),
        migrations.RenameField(
            model_name='react',
            old_name='tunel_min',
            new_name='min',
        ),
    ]
