# Generated by Django 4.2.6 on 2023-11-01 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_tunel_max_react_max_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='react',
            name='max',
            field=models.FloatField(max_length=5),
        ),
        migrations.AlterField(
            model_name='react',
            name='min',
            field=models.FloatField(max_length=5),
        ),
    ]
